### ISSUE TITLE
does not work benchamrk

### ISSUE THREAD

**Issue by ZloyDyadka** [M6Web/websocket-bench#13]
Test does not work on the latest version of Node JS
![asdasd](https://f.cloud.github.com/assets/5509643/2178343/6a6f5c76-9664-11e3-8675-95535e1fc920.png)

**Comment by JamCode** [comment]
i cannot work on the socket.io test

test command is :websocket-bench -p io http://***.74.102.178:10666

code is here

var io = require('socket.io').listen(10666);
log.logPrint(config.logLevel.DEBUG, "start listen socket");
io.sockets.on('connection', function(socket) {
        log.logPrint(config.logLevel.DEBUG, process.pid + " get the socket:" + socket.id);
});
