### ISSUE TITLE
socket.io 1.0

### ISSUE THREAD

**Issue by dibu28** [M6Web/websocket-bench#30]
was working before, now errors with socket.io 1.0

**Comment by hperello** [comment]
Same here...

**Comment by pronskiy** [comment]
To fix that you could update socket.io dependencies to the latest in the package.json:
```
"socket.io-client": "~1.3.5",
...
"socket.io": "~1.3.5",
```
and then run `npm install`

**Comment by hperello** [comment]
Thank you! Now works
